export const styles = {
  container: {
    fontFamily: "'Inter', system-ui, sans-serif",
    padding: "24px",
    maxWidth: "1400px",
    margin: "0 auto",
    backgroundColor: "#f8fafc",
    minHeight: "100vh",
  },
  title: {
    fontSize: "32px",
    fontWeight: "800",
    marginBottom: "24px",
    color: "#1e293b",
    textAlign: "center",
  },
  card: {
    backgroundColor: "white",
    border: "1px solid #e2e8f0",
    borderRadius: "16px",
    padding: "24px",
    marginBottom: "24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  subtitle: {
    fontSize: "20px",
    fontWeight: "600",
    marginTop: 0,
    marginBottom: "16px",
    color: "#334155",
  },
  button: {
    backgroundColor: "#3b82f6",
    color: "white",
    padding: "8px 16px",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    fontWeight: "500",
    transition: "background-color 0.2s",
  },
  buttonSecondary: {
    backgroundColor: "#64748b",
    color: "white",
    padding: "8px 16px",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    fontWeight: "500",
    transition: "background-color 0.2s",
  },
  flexContainer: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  info: {
    color: "#64748b",
    fontSize: "14px",
    marginTop: "8px",
  },
};